name: vidm
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.2
  - numpy=1.19.2
  - pip:
    - torch==1.13.1
    - torchvision==0.14.1
    - albumentations==0.4.3
    - opencv-python==4.1.2.30
    - funcy==1.18
    - pudb==2019.2
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.2
    - pytorch-lightning==1.4.2
    - omegaconf==2.1.1
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops==0.3.0
    - torch-fidelity==0.3.0
    - torchmetrics==0.6
    - transformers==4.19.2
    - h5py==3.7.0
    - -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
    - -e .
